#version: '3.8'

services:
  rabbitmq:
    hostname: r1
    image: rabbitmq:3.13-management-alpine
    ports:
      - "15672:15672" # Management nach außen verfügbar

  app1:
    hostname: a1
    image: crickets:latest
    environment:
      - AMQP_HOST=r1
    depends_on:
      - rabbitmq
    ports:
      - "8081:8080"

  app2:
    hostname: a2
    image: crickets:latest
    environment:
      - AMQP_HOST=r1
    depends_on:
      - rabbitmq
    ports:
      - "8082:8080"

  app3:
    hostname: a3
    image: crickets:latest
    environment:
      - AMQP_HOST=r1
    depends_on:
      - rabbitmq
    ports:
      - "8083:8080"
